/* GUI Studio — app entry point. Generated by Flipper GUI Studio. */

#include "gui_studio_scene.h"
#include <furi.h>

/* Called whenever a button's custom event fires. This overrides the weak
 * default in gui_studio_scene.c — put your app logic here. */
void gui_studio_on_event(int32_t event, GuiStudioModel* state) {
    UNUSED(state);
    switch(event) {
        // case 1: /* handle custom event 1 */ break;
        default:
            UNUSED(event);
            break;
    }
}

int32_t gui_studio_app(void* p) {
    UNUSED(p);
    GuiStudioScene* scene = gui_studio_scene_alloc();
    gui_studio_scene_run(scene);
    gui_studio_scene_free(scene);
    return 0;
}
